services:
  - type: web
    name: steel-tructural-analyzer
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
