[gcp_service_account]
type = "service_account"
project_id = "struktur-sni-baja"
private_key_id = "de2b2393963efb95fe0dc561984f3ae77ae468de"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMDv+QT6RCf+ID
kAdaGuCkw6AeUhMYcREOPJOPH5ufr36i5nAaqcPROjQErcvOWWuRQIbzvqBlV4z1
q9990nURCBn6f7PV7JMmzEYPfR/YprvVwEh1q0xfSDIMKrEW1hYUJrnPHWcClpx0
ODZU/ve8L4a7WVxSqk7+6NP0BH17CENLgz58BEgU6zq9Siz4Nra2x+zP2bDWnPpj
Piz3oZorXKy+WBoNYPW4emp4CDobT+pqGUlJKUdHKNYZ8v9i1CpKB3HeJmq1T7SI
LLUnXj7Ohf2aqK4ulD9ujQY2dmnb/mfhwGfjYVhtFLVr4au5EdBHMBqIk4BJvwzn
qDC8DoAhAgMBAAECggEAAIxx2Hy2CrfxHtknKDFgjlhGOfKkby3VpBnIV5Au2ijt
3Ai5P1Os6N34PvCeCREBg6d5z7FqGSjLgnSBrcMCf/TGrGPKUzeATmvX7HLFwo6W
Drrvc4H3FnlrlystJKwy/1F6sUzEvYpqg01DUNil/y5ULDTPLDc5G/fxmcs5OaQA
sEbvyXPm27bmsUYmtOXfmBhlOoNlT0pDIVKBbaJ2ZgBnBaGlYrRY1JQ/P8YUGLAT
UPkhjjT0piU7D89lMOjbhk922Z5Ud4KypvQYyPdAa+h5VMpksmjTCIufmxV9Ma7S
rFmQRn7+ndSQnTyRi+WpLhoBXfdI+g8NZqu3iivrAQKBgQD3bBbOURrjd9OYXyOY
9po5285lwOFFl97ex6PL/rgC0rHJudRfhuJGEofvkJzp9sZZyxCJqHpKQFHzasPv
gqPYE2Q+kpnFp6Yrvwh3iQFlrJnJzHcoaLQJ8c85TwJbZPhobVQHZhkh3oaqw8NS
W7NDlYSM7LjKYanuooIApXzSQQKBgQDTIgzXYdKaOpdXZDcowX0NxzGeBda2yV3J
L/D7jpESCnkXA6XSWkIHHNg9Ykk6bdDhyNszAeIuC7XQ2kNgEe7GkQvWUUf5Ujqx
sFBJQTfvtMSZinY+RPnLxMvnA82hTDcdA7yz15FeyuYgvS4MuJOMBv5WadhASnnK
ouYb6MJ14QKBgEevfXwRa6T0Fs5S4lFzQYP593brx1kOg3gwh3iXOGE5AmHcAXgb
8Hs060WxtITlBtsFRqlbsvLIZ/YKvPIr+6SjGaw3dW4bAL4z/xQDEfCPbY9WOj/u
9hrbgJquFZS9UGuRIYNzRVzWyFW5mmHGR84RB/J8s52PZljJpLjjOaMBAoGBAIqe
THgMjc0cssh5z40+m/Az2+u4QaR4yM6SX1GJ5M1HewEVMAXPpJIu6fpDUXi/KOlU
ijYPAoTgw1qAMsQcgfx0tqTbcLnMtyR6cfvmiecjdACq278+YhLa/lSKNrOz6mtu
TLJ20ca+yCCulFFdzeGdpdbuX0C2pQfZs+KXCzWBAoGBALXgpOX0uaUQbWc83fMc
brBfePaAB8gNf2Fbm3AuAqw9lW/oboHoBXimDbw1l+zrnfMFFzljwlwudxOfoJnu
Oulfj7R3HR6crIQ5MDUJpuzMqDE9vHhmRFeCy0nsPsJJNWTq9JZNO8ZI8VawHcJp
SIezXBgYA+2UiAt3N4gdFX9D
-----END PRIVATE KEY-----"""
client_email = "struktur-baja-sni@struktur-sni-baja.iam.gserviceaccount.com"
client_id = "100391346862569581157"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/struktur-baja-sni%40struktur-sni-baja.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
